import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher/ThemeSwitcher";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
          <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          {/* <ThemeSwitcher /> */}
            <main className="w-screen h-screen overflow-x-hidden overflow-y-auto">
              <Navbar />
              {children}
              <Footer />
              <Toaster />
            </main>
        </ThemeProvider>
          </body>
      </AuthProvider>
    </html>
  );
}
